=== devanshudave1901/MobileDevelopmentWebsite-master/Lab3 content/projects.dtd
<!ELEMENT projects (company,project+)>
<!ELEMENT company (companyName,companyAddress,logo,webAddress?,email,phone+)>
<!ELEMENT companyName (#PCDATA)>
<!ELEMENT companyAddress (#PCDATA)>
<!ELEMENT logo (#PCDATA)>
<!ELEMENT webAddress (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT project (title ,managers ,teams,clients*,projectDate,projectComments )>
<!ATTLIST project
     projid CDATA #REQUIRED

>
<!ELEMENT title (#PCDATA)>
<!ELEMENT managers (manager+)>
<!ELEMENT manager (firstName,middleName?,lastName,managerPhone,managerEmail*)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT middleName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT managerPhone (#PCDATA)>



<!ATTLIST managerPhone type (managerHome|managerOffice) "managerHome">
<!ELEMENT managerEmail (#PCDATA)>
<!ELEMENT teams (team)>
<!ELEMENT team (leader ,developer+,tester?,documenter*)>
<!ELEMENT leader (#PCDATA)>
<!ELEMENT developer (#PCDATA)>
<!ELEMENT tester (#PCDATA)>
<!ELEMENT documenter (#PCDATA)>
<!ELEMENT clients (client*)>

<!ELEMENT client (clientName,address,clientEmail,clientPhone)>
<!ATTLIST client
     clientid CDATA #REQUIRED

>
<!ELEMENT clientName (#PCDATA)>
<!ELEMENT address (street?,city,country, postalCode?)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT postalCode (#PCDATA)>
<!ELEMENT clientEmail (#PCDATA)>
<!ELEMENT clientPhone (#PCDATA)>

<!ELEMENT projectDate (#PCDATA)>
<!ATTLIST projectDate
     start CDATA #REQUIRED
     end   CDATA #IMPLIED
>
<!ELEMENT projectComments (#PCDATA)>

=== devanshudave1901/MobileDevelopmentWebsite-master/Lab3 content/projects.xml
<?xml version="1.0" standalone="no"?>
<!-- projects.xml             -->
<!DOCTYPE projects SYSTEM "projects.dtd">

<projects>
	<company>
		<companyName>Medical Com</companyName>
		<companyAddress>12 medical Street</companyAddress>
		<logo>ME</logo>
		<webAddress>medicalCom.com</webAddress>
		<email>dsd@gmail.com</email>
		<phone>211-111-1111</phone>
	</company>
	<project projid  = "PO1">
		<title>Pharmacy medicine Filter System</title>
		<managers>
			<manager>
				<firstName>Devanshu</firstName>
				<middleName>Maulik</middleName>
				<lastName>Dave</lastName>
				<managerPhone type="managerHome"></managerPhone>
		
				<managerEmail>dev@gmail</managerEmail>
			
			</manager>
			
		</managers>
		<teams>
			<team>
				<leader>Adam</leader>
				<developer>Nick</developer>
				<tester>Oliver</tester>
				<documenter>William</documenter>
			</team>
		</teams>
		<clients>
			<client clientid = "c12">
				<clientName>Liam</clientName>
				<address>
					<street>22 CLIENT street</street>
					<city>Toronto</city>
					<country>Canada</country>
					<postalCode>S3E 3D3</postalCode>
				</address>
				<clientEmail>liam@gmail.com</clientEmail>
				<clientPhone>2333333456</clientPhone>				
			</client>
		</clients>
		
		<projectDate start="23-09-2020" end="23-09-2022"></projectDate>
		<projectComments>Good Project and will impact a buisness in a positive way</projectComments>
	</project>

</projects>
